# Generated by Django 4.1.3 on 2022-11-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variação'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variação',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
