# Generated by Django 4.1.3 on 2022-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_variação_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variação',
            new_name='Variacao',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variavel'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
