# Generated by Django 4.1.3 on 2022-11-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao',
            new_name='variação',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='variacao_id',
            new_name='variação_id',
        ),
    ]
